### ISSUE TITLE
Step -1 from index 0

### ISSUE THREAD

**Issue by dmikots** [cbepxbeo/page-viewer#1]
Hi, how can I go to array.last from array.first while I use index and buttons

**Comment by cbepxbeo** [comment]
Hello. I did not make such an implementation. But thanks, great idea.

**Comment by dmikots** [comment]
I have questions about the implementation. How can I get in contact ? I have my telegram on my page

> Hello. I did not make such an implementation. But thanks, great idea.

**Comment by cbepxbeo** [comment]
I have updated the package version, now you can use the external controller and use the go to last view method.
